#!/usr/bin/env bash

WALLPAPERS_DIR="$HOME/.local/share/wallpapers"
STYLE="$HOME/.config/rofi/scripts/wallpaper/style.rasi"

# Pick a wallpaper via rofi
choice=$(
	ls --escape "$WALLPAPERS_DIR" |
		while read -r A; do
		echo -en "$A\x00icon\x1f$WALLPAPERS_DIR/$A\n"
		done |
	rofi -dmenu -i -show-icons -p "Wallpaper" -theme "$STYLE"
)

[ -z "$choice" ] && exit 0

wp="$WALLPAPERS_DIR/$choice"

killall hyprpaper
hyprpaper &

sleep 0.2
for monitor in $(hyprctl monitors -j | jq -r '.[].name'); do
	hyprctl hyprpaper wallpaper "$monitor,$wp"
done
